title: Mike Watson
description: > # this means to ignore newlines until "baseurl:"
  I’m an IT and cybersecurity professional with a passion for network security, 
  ethical hacking, and cloud computing. This blog is your go-to resource for my 
  projects, insights, and industry updates.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mike Watson # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am an Air Force veteran with a passion for tech and an ever expanding my knowledge towards CyberSecurity. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: elementary-221b # add your Github handle
social-linkedin: https://www.linkedin.com/in/my-dear-watson/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
